name: Terraform

# on: # [push, workflow_dispatch]
#   # - push
#   - workflow_dispatch:

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      arc_name:
        description: 'Target ARC name used for `runs-on` in job'
        default: runner-scale-set-kubernetes

# jobs:
#   # test-connection-1:
#   #   runs-on:
#   #     - ${{ inputs.arc_name }}

jobs:
  Terraform_Build:
    runs-on:
      - ${{ inputs.arc_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: terraform setup
        uses: hashicorp/setup-terraform@v3

      - name: check workdir
        run: pwd
        
      - name: terraform test
        run: terraform version