name: Terraform

# on: # [push, workflow_dispatch]
#   # - push
#   - workflow_dispatch:

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      arc_name:
        description: 'Target ARC name used for `runs-on` in job'
        default: runner-scale-set-kubernetes

# jobs:
#   # test-connection-1:
#   #   runs-on:
#   #     - ${{ inputs.arc_name }}

jobs:
  Terraform_Build:
    runs-on:
      - ${{ inputs.arc_name }}
    defaults:
      run:
        working-directory: ./sa
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: terraform setup
        uses: hashicorp/setup-terraform@v3

      - name: check workdir
        run: pwd

      - name: terraform test
        run: terraform version
    
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
      
      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true
